(() => {
'use strict';
const cfg=window.CSI_CONFIG||{}, seed=window.CSI_SEED||{people:[],attendance:[]};
const configured=!!(cfg.supabaseUrl&&cfg.supabaseAnonKey); const sb=configured?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const S={user:null,profile:null,classes:[],people:[],attendance:[],users:[],assignments:[],view:'dashboard',demo:false,attendanceDraft:{},selectedGroup:'',selectedDate:'',reportFrom:'',reportTo:'',reportGroup:'all'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function initials(n=''){return n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?';}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function iso(d){return d.toISOString().slice(0,10)} function parseDate(s){return new Date(s+'T12:00:00')}
function fmtDate(s,opt={day:'2-digit',month:'short',year:'numeric'}){return s?parseDate(s).toLocaleDateString('en-IN',opt):'—'}
function sundayOnOrBefore(d=new Date()){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-x.getDay());return iso(x)}
function academicBounds(date=new Date()){let y=date.getFullYear(),m=cfg.academicYearStartMonth||6;if(date.getMonth()+1<m)y--;return {start:`${y}-${String(m).padStart(2,'0')}-01`,end:`${y+1}-${String(m-1||12).padStart(2,'0')}-${new Date(y+1,m-1,0).getDate().toString().padStart(2,'0')}`,label:`${y}–${String(y+1).slice(-2)}`}}
function allowedGroups(){if(S.profile?.role==='admin')return [...new Set(S.people.filter(p=>p.active).map(p=>p.group_name))].sort();return [...S.classes].sort()}
function statusNorm(v){v=String(v||'').toLowerCase();return v.startsWith('p')?'Present':v.startsWith('a')?'Absent':'Unmarked'}
function showModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')} function closeModal(){$('#modal').classList.add('hidden')}
function todayChip(){$('#todayChip').textContent=new Date().toLocaleDateString('en-IN',{weekday:'short',day:'2-digit',month:'short'})}
function setAuthUI(){const logged=!!S.profile;$('#authView').classList.toggle('hidden',logged);$('#appView').classList.toggle('hidden',!logged);if(logged){const n=S.profile.full_name||S.user?.email||'User';$('#sideUserName').textContent=n;$('#sideRole').textContent=S.profile.role==='admin'?'Administrator':'Teacher';$('#avatar').textContent=initials(n);$('#topAvatar').textContent=initials(n);$$('.admin-only').forEach(x=>x.classList.toggle('hidden',S.profile.role!=='admin'));todayChip();render();}else{$('#demoBox').classList.toggle('hidden',configured)}}
function localLoad(){const saved=JSON.parse(localStorage.getItem('csi_demo_data')||'null');if(saved){S.people=saved.people;S.attendance=saved.attendance}else{S.people=seed.people.map(x=>({...x}));S.attendance=seed.attendance.map(x=>({...x,id:`seed-${x.person_id}-${x.attendance_date}`}))}S.profile={id:'demo-admin',full_name:'Admin Preview',role:'admin'};S.user={id:'demo-admin',email:'preview@local'};S.classes=[];S.demo=true;autoBackup('preview-start')}
function localSave(){localStorage.setItem('csi_demo_data',JSON.stringify({people:S.people,attendance:S.attendance}));autoBackup('local-save')}
function autoBackup(reason){const snap={created_at:new Date().toISOString(),reason,people:S.people,attendance:S.attendance};localStorage.setItem('csi_last_backup',JSON.stringify(snap))}
async function loadCloud(){const {data:{session}}=await sb.auth.getSession();if(!session){S.user=S.profile=null;return}S.user=session.user;let {data:p,error}=await sb.from('profiles').select('*').eq('id',S.user.id).single();if(error)throw error;S.profile=p;let classQ=await sb.from('teacher_classes').select('group_name').eq('user_id',S.user.id);S.classes=(classQ.data||[]).map(x=>x.group_name);let pq=await sb.from('people').select('*').order('group_name').order('name');if(pq.error)throw pq.error;S.people=pq.data||[];let aq=await sb.from('attendance').select('*').order('attendance_date');if(aq.error)throw aq.error;S.attendance=aq.data||[];if(S.profile.role==='admin'){let uq=await sb.from('profiles').select('id,full_name,role,created_at').order('full_name');S.users=uq.data||[];let tq=await sb.from('teacher_classes').select('*');S.assignments=tq.data||[]}autoBackup('cloud-sync')}
async function init(){S.selectedDate=sundayOnOrBefore();const b=academicBounds();S.reportFrom=b.start;S.reportTo=Math.min(b.end,iso(new Date()));bindStatic();if(configured){try{await loadCloud()}catch(e){console.error(e);toast('Could not load cloud data')}sb.auth.onAuthStateChange(async()=>{try{await loadCloud();setAuthUI()}catch(e){console.error(e)}})}setAuthUI()}
function bindStatic(){
 $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();if(!configured)return;const {error}=await sb.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error)toast(error.message)});
 $('#showSignup').onclick=()=>$('#signupForm').classList.toggle('hidden');
 $('#signupForm').addEventListener('submit',async e=>{e.preventDefault();if(!configured)return;const {error}=await sb.auth.signUp({email:$('#signupEmail').value.trim(),password:$('#signupPassword').value,options:{data:{full_name:$('#signupName').value.trim()}}});toast(error?error.message:'Account created. Check your email if confirmation is enabled, then ask the admin to assign your class.')});
 $('#demoLogin').onclick=()=>{localLoad();setAuthUI()};$('#logoutBtn').onclick=async()=>{if(S.demo){S.user=S.profile=null;S.demo=false;setAuthUI()}else await sb.auth.signOut()};
 $('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#modalClose').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
 $('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;switchView(b.dataset.view)});
}
function switchView(v){S.view=v;$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#sidebar').classList.remove('open');render()}
function render(){const map={dashboard:['Academic year','Dashboard'],attendance:['Sunday register','Mark attendance'],people:['Roster','People'],reports:['Analytics & exports','Reports'],users:['Access control','Accounts'],backup:['Data safety','Backup']};const [eye,title]=map[S.view]||map.dashboard;$('#viewEyebrow').textContent=eye;$('#viewTitle').textContent=title;const fn={dashboard:renderDashboard,attendance:renderAttendance,people:renderPeople,reports:renderReports,users:renderUsers,backup:renderBackup}[S.view]||renderDashboard;fn();}
function attendanceFor(p,date){return S.attendance.find(a=>String(a.person_id)===String(p.id)&&a.attendance_date===date)}
function calcRate(records){const marked=records.filter(a=>['Present','Absent'].includes(statusNorm(a.status)));return marked.length?Math.round(100*marked.filter(a=>statusNorm(a.status)==='Present').length/marked.length):0}
function historyForPerson(id,start,end){return S.attendance.filter(a=>String(a.person_id)===String(id)&&(!start||a.attendance_date>=start)&&(!end||a.attendance_date<=end)).sort((a,b)=>a.attendance_date.localeCompare(b.attendance_date))}
function streak(id,kind='current'){const h=historyForPerson(id).filter(a=>['Present','Absent'].includes(statusNorm(a.status))).sort((a,b)=>b.attendance_date.localeCompare(a.attendance_date));if(!h.length)return 0;if(kind==='current'){let n=0;for(const a of h){if(statusNorm(a.status)==='Present')n++;else break}return n}let best=0,n=0;for(const a of [...h].reverse()){if(statusNorm(a.status)==='Present'){n++;best=Math.max(best,n)}else n=0}return best}
function absenceStreak(id){const h=historyForPerson(id).filter(a=>['Present','Absent'].includes(statusNorm(a.status))).sort((a,b)=>b.attendance_date.localeCompare(a.attendance_date));let n=0;for(const a of h){if(statusNorm(a.status)==='Absent')n++;else break}return n}
function renderDashboard(){const b=academicBounds(), groups=allowedGroups(), ids=new Set(S.people.filter(p=>p.active&&groups.includes(p.group_name)).map(p=>String(p.id))), ay=S.attendance.filter(a=>ids.has(String(a.person_id))&&a.attendance_date>=b.start&&a.attendance_date<=b.end), latest=[...new Set(ay.map(a=>a.attendance_date))].sort().pop(), latestRows=latest?ay.filter(a=>a.attendance_date===latest):[];const students=S.people.filter(p=>p.active&&groups.includes(p.group_name)&&p.role==='Student');const follow=students.map(p=>({p,n:absenceStreak(p.id)})).filter(x=>x.n>=(cfg.chronicAbsenceThreshold||3)).sort((a,b)=>b.n-a.n);const streaks=students.map(p=>({p,n:streak(p.id)})).filter(x=>x.n).sort((a,b)=>b.n-a.n).slice(0,7);let classRates=groups.map(g=>{const pids=new Set(S.people.filter(p=>p.active&&p.group_name===g).map(p=>String(p.id)));return {g,rate:calcRate(ay.filter(a=>pids.has(String(a.person_id))))}});
 $('#content').innerHTML=`<section class="hero-strip"><div><p class="eyebrow">${esc(b.label)}</p><h3>Good ${new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}, ${esc((S.profile.full_name||'').split(' ')[0])}</h3><p>${S.profile.role==='admin'?'A clear view of attendance, follow-ups and every class.':`Your assigned classes: ${esc(groups.join(', ')||'awaiting assignment')}.`}</p></div><div class="hero-actions"><button class="btn primary" id="quickAttendance">Mark attendance</button><button class="btn secondary" id="quickReport">Reports</button></div></section>
 <div class="stats"><div class="stat-card"><span>Active students</span><strong>${students.length}</strong><small>${groups.length} class${groups.length===1?'':'es'} in view</small></div><div class="stat-card"><span>${esc(b.label)} attendance</span><strong>${calcRate(ay)}%</strong><small>${ay.length} marked records</small></div><div class="stat-card"><span>Latest Sunday</span><strong>${latest?calcRate(latestRows)+'%':'—'}</strong><small>${latest?fmtDate(latest):'No attendance yet'}</small></div><div class="stat-card"><span>Follow-up alerts</span><strong>${follow.length}</strong><small>${cfg.chronicAbsenceThreshold||3}+ consecutive absences</small></div></div>
 <div class="grid-2"><section class="panel"><div class="panel-head"><div><h3>Class comparison</h3><p class="muted tiny">Attendance across ${esc(b.label)}</p></div></div><div class="class-bars">${classRates.length?classRates.map(x=>`<div class="bar-row"><span>${esc(x.g)}</span><div class="track"><div class="fill" style="width:${x.rate}%"></div></div><b>${x.rate}%</b></div>`).join(''):'<div class="empty">No assigned classes yet.</div>'}</div></section>
 <section class="panel"><div class="panel-head"><div><h3>Needs a check-in</h3><p class="muted tiny">Consecutive recorded absences</p></div></div><div class="alert-list">${follow.length?follow.slice(0,7).map(x=>personRow(x.p,`<span class="badge bad">${x.n} Sundays</span>`)).join(''):'<div class="empty">No chronic-absence alerts 🎉</div>'}</div></section></div>
 <div class="grid-equal" style="margin-top:18px"><section class="panel"><div class="panel-head"><div><h3>Current attendance streaks</h3><p class="muted tiny">Students with consecutive presents</p></div></div><div class="streak-list">${streaks.length?streaks.map(x=>personRow(x.p,`<span class="badge good">${x.n} in a row</span>`)).join(''):'<div class="empty">Streaks will appear after more Sundays are marked.</div>'}</div></section><section class="panel"><div class="panel-head"><div><h3>Monthly trend</h3><p class="muted tiny">${esc(b.label)} overall attendance</p></div></div>${monthlyChart(ay,b)}</section></div>`;
 $('#quickAttendance').onclick=()=>switchView('attendance');$('#quickReport').onclick=()=>switchView('reports');bindProfileLinks();}
function personRow(p,end=''){return `<div class="person-row"><div class="avatar">${initials(p.name)}</div><div class="meta"><button class="link-btn profile-link" data-id="${p.id}"><b>${esc(p.name)}</b></button><small>${esc(p.group_name)}</small></div>${end}</div>`}
function monthlyChart(rows,b){let buckets={};rows.forEach(a=>{let k=a.attendance_date.slice(0,7);(buckets[k]??=[]).push(a)});let keys=Object.keys(buckets).sort();if(!keys.length)return '<div class="empty">Mark more Sundays to build the trend.</div>';return `<div class="chart">${keys.map(k=>{let r=calcRate(buckets[k]);let d=parseDate(k+'-01');return `<div class="chart-col"><div class="column" style="height:${Math.max(4,r*1.7)}px" title="${r}%"></div><small>${d.toLocaleDateString('en-IN',{month:'short'})}</small></div>`}).join('')}</div>`}
function renderAttendance(){const groups=allowedGroups();if(!S.selectedGroup||!groups.includes(S.selectedGroup))S.selectedGroup=groups[0]||'';const roster=S.people.filter(p=>p.active&&p.group_name===S.selectedGroup).sort((a,b)=>a.name.localeCompare(b.name));S.attendanceDraft={};roster.forEach(p=>S.attendanceDraft[p.id]=statusNorm(attendanceFor(p,S.selectedDate)?.status));const isSun=parseDate(S.selectedDate).getDay()===0;$('#content').innerHTML=`${!groups.length?'<div class="notice">Your account has no assigned classes yet. Ask the Sunday School admin to assign one.</div>':''}<div class="toolbar"><label class="field"><span>Sunday date</span><input type="date" id="attDate" value="${S.selectedDate}"></label><label class="field grow"><span>Class</span><select id="attGroup">${groups.map(g=>`<option ${g===S.selectedGroup?'selected':''}>${esc(g)}</option>`).join('')}</select></label><button class="btn ghost" id="allPresent">All present</button><button class="btn ghost" id="allAbsent">All absent</button></div>${!isSun?'<div class="notice">This date is not a Sunday. You can review it, but saving is disabled until you select a Sunday.</div>':''}<div class="attendance-head"><div><h3 style="margin:0;font-family:'Playfair Display',serif">${esc(S.selectedGroup||'No class')}</h3><p class="muted tiny">${fmtDate(S.selectedDate,{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</p></div><div class="attendance-summary"><span class="summary-pill" id="presentCount"></span><span class="summary-pill" id="absentCount"></span><span class="summary-pill" id="unmarkedCount"></span></div></div><div class="roster" id="roster">${roster.map(attCard).join('')||'<div class="empty">No people in this class.</div>'}</div><div class="save-bar"><span class="muted tiny">Changes are saved to the shared database when you press Save.</span><button class="btn primary" id="saveAttendance" ${!isSun||!roster.length?'disabled':''}>Save attendance</button></div>`;bindAttendance();updateCounts()}
function attCard(p){const st=S.attendanceDraft[p.id];return `<div class="attendance-card"><div class="avatar">${initials(p.name)}</div><div class="meta"><b>${esc(p.name)}</b><small>${esc(p.role)}</small></div><div class="status-toggle" data-id="${p.id}"><button class="present ${st==='Present'?'active':''}" data-status="Present">Present</button><button class="absent ${st==='Absent'?'active':''}" data-status="Absent">Absent</button></div></div>`}
function bindAttendance(){$('#attDate').onchange=e=>{S.selectedDate=e.target.value;renderAttendance()};$('#attGroup').onchange=e=>{S.selectedGroup=e.target.value;renderAttendance()};$('#roster').onclick=e=>{const b=e.target.closest('[data-status]');if(!b)return;const id=b.parentElement.dataset.id;S.attendanceDraft[id]=b.dataset.status;renderAttendance()};$('#allPresent').onclick=()=>{Object.keys(S.attendanceDraft).forEach(id=>S.attendanceDraft[id]='Present');renderAttendance()};$('#allAbsent').onclick=()=>{Object.keys(S.attendanceDraft).forEach(id=>S.attendanceDraft[id]='Absent');renderAttendance()};$('#saveAttendance').onclick=saveAttendance}
function updateCounts(){const vals=Object.values(S.attendanceDraft);$('#presentCount').textContent=`${vals.filter(x=>x==='Present').length} present`;$('#absentCount').textContent=`${vals.filter(x=>x==='Absent').length} absent`;$('#unmarkedCount').textContent=`${vals.filter(x=>x==='Unmarked').length} unmarked`}
async function saveAttendance(){const rows=Object.entries(S.attendanceDraft).filter(([,st])=>st!=='Unmarked').map(([id,status])=>({person_id:Number(id),attendance_date:S.selectedDate,status}));if(S.demo){for(const r of rows){const i=S.attendance.findIndex(a=>String(a.person_id)===String(r.person_id)&&a.attendance_date===r.attendance_date);if(i>=0)S.attendance[i]={...S.attendance[i],...r};else S.attendance.push({...r,id:`local-${Date.now()}-${r.person_id}`})}localSave();toast('Attendance saved in this browser');renderAttendance();return}const {error}=await sb.from('attendance').upsert(rows,{onConflict:'person_id,attendance_date'});if(error)return toast(error.message);await loadCloud();toast('Attendance saved');renderAttendance()}
function renderPeople(){if(S.profile.role!=='admin')return switchView('dashboard');const groups=[...new Set(S.people.map(p=>p.group_name))].sort();$('#content').innerHTML=`<div class="toolbar"><label class="field grow"><span>Search people</span><input id="peopleSearch" placeholder="Search name or class"></label><label class="field"><span>Class</span><select id="peopleGroup"><option value="all">All classes</option>${groups.map(g=>`<option>${esc(g)}</option>`).join('')}</select></label><button class="btn primary" id="addPerson">+ Add person</button></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Class</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody id="peopleBody"></tbody></table></div>`;const draw=()=>{let q=$('#peopleSearch').value.toLowerCase(),g=$('#peopleGroup').value;let rows=S.people.filter(p=>(g==='all'||p.group_name===g)&&(`${p.name} ${p.group_name}`.toLowerCase().includes(q)));$('#peopleBody').innerHTML=rows.map(p=>`<tr><td><button class="link-btn profile-link" data-id="${p.id}">${esc(p.name)}</button></td><td>${esc(p.group_name)}</td><td>${esc(p.role)}</td><td><span class="badge ${p.active?'good':'warn'}">${p.active?'Active':'Archived'}</span></td><td><button class="text-btn edit-person" data-id="${p.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No matching people.</td></tr>';bindProfileLinks();$$('.edit-person').forEach(b=>b.onclick=()=>openPerson(Number(b.dataset.id)));};$('#peopleSearch').oninput=draw;$('#peopleGroup').onchange=draw;$('#addPerson').onclick=()=>openPerson();draw()}
function openPerson(id=null){const p=id?S.people.find(x=>x.id===id):null;const groups=[...new Set(S.people.map(x=>x.group_name))].sort();showModal(`<h3>${p?'Edit person':'Add person'}</h3><form id="personForm" class="form-stack"><label>Full name<input id="personName" required value="${esc(p?.name||'')}"></label><label>Class / group<input id="personGroup" list="groupList" required value="${esc(p?.group_name||'')}"><datalist id="groupList">${groups.map(g=>`<option value="${esc(g)}">`).join('')}</datalist></label><label>Role<select id="personRole"><option ${p?.role==='Student'?'selected':''}>Student</option><option ${p?.role==='Teacher'?'selected':''}>Teacher</option><option ${p?.role==='Volunteer'?'selected':''}>Volunteer</option></select></label>${p?`<label class="check"><input id="personActive" type="checkbox" ${p.active?'checked':''}> Active on roster</label>`:''}<button class="btn primary" type="submit">${p?'Save changes':'Add person'}</button></form>`);$('#personForm').onsubmit=async e=>{e.preventDefault();const row={name:$('#personName').value.trim(),group_name:$('#personGroup').value.trim(),role:$('#personRole').value,active:p?$('#personActive').checked:true};if(S.demo){if(p)Object.assign(p,row);else S.people.push({...row,id:Math.max(0,...S.people.map(x=>x.id))+1});localSave()}else{const q=p?await sb.from('people').update(row).eq('id',p.id):await sb.from('people').insert(row);if(q.error)return toast(q.error.message);await loadCloud()}closeModal();toast(p?'Person updated':'Person added');renderPeople()}}
function renderReports(){const groups=allowedGroups();$('#content').innerHTML=`<section class="panel"><div class="panel-head"><div><h3>Attendance report</h3><p class="muted tiny">Choose any date range and class, then download the data.</p></div></div><div class="toolbar"><label class="field"><span>From</span><input id="reportFrom" type="date" value="${S.reportFrom}"></label><label class="field"><span>To</span><input id="reportTo" type="date" value="${S.reportTo}"></label><label class="field grow"><span>Class</span><select id="reportGroup"><option value="all">All permitted classes</option>${groups.map(g=>`<option ${S.reportGroup===g?'selected':''}>${esc(g)}</option>`).join('')}</select></label><button class="btn ghost" id="csvBtn">Download CSV</button><button class="btn primary" id="jsonBtn">Download JSON</button></div><div id="reportSummary"></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Name</th><th>Class</th><th>Status</th></tr></thead><tbody id="reportBody"></tbody></table></div></section>`;const draw=()=>{S.reportFrom=$('#reportFrom').value;S.reportTo=$('#reportTo').value;S.reportGroup=$('#reportGroup').value;let data=reportRows();$('#reportSummary').innerHTML=`<div class="stats"><div class="stat-card"><span>Records</span><strong>${data.length}</strong></div><div class="stat-card"><span>Attendance</span><strong>${calcRate(data)}%</strong></div><div class="stat-card"><span>Present</span><strong>${data.filter(x=>x.status==='Present').length}</strong></div><div class="stat-card"><span>Absent</span><strong>${data.filter(x=>x.status==='Absent').length}</strong></div></div>`;$('#reportBody').innerHTML=data.slice().sort((a,b)=>b.attendance_date.localeCompare(a.attendance_date)||a.name.localeCompare(b.name)).map(r=>`<tr><td>${fmtDate(r.attendance_date)}</td><td>${esc(r.name)}</td><td>${esc(r.group_name)}</td><td><span class="badge ${r.status==='Present'?'good':'bad'}">${r.status}</span></td></tr>`).join('')||'<tr><td colspan="4" class="empty">No attendance in this range.</td></tr>'};['reportFrom','reportTo','reportGroup'].forEach(id=>$('#'+id).onchange=draw);$('#csvBtn').onclick=()=>downloadCSV(reportRows());$('#jsonBtn').onclick=()=>downloadFile(`csi-attendance-${S.reportFrom}-to-${S.reportTo}.json`,JSON.stringify(reportRows(),null,2),'application/json');draw()}
function reportRows(){const groups=allowedGroups(), people=new Map(S.people.map(p=>[String(p.id),p]));return S.attendance.map(a=>({...a,status:statusNorm(a.status),...(people.get(String(a.person_id))||{})})).filter(r=>groups.includes(r.group_name)&&r.attendance_date>=S.reportFrom&&r.attendance_date<=S.reportTo&&(S.reportGroup==='all'||r.group_name===S.reportGroup)&&['Present','Absent'].includes(r.status))}
function downloadCSV(data){let rows=[['Date','Name','Class','Role','Status'],...data.map(r=>[r.attendance_date,r.name,r.group_name,r.role,r.status])];let csv=rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n');downloadFile(`csi-attendance-${S.reportFrom}-to-${S.reportTo}.csv`,csv,'text/csv;charset=utf-8')}
function downloadFile(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function renderUsers(){if(S.profile.role!=='admin')return switchView('dashboard');const teachers=S.users.filter(u=>u.role==='teacher');const groups=[...new Set(S.people.map(p=>p.group_name))].sort();$('#content').innerHTML=`<div class="notice">Teachers register from the sign-in page. Once their account appears here, assign the class(es) they are allowed to access. Admin accounts can manage everything.</div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Role</th><th>Assigned classes</th><th></th></tr></thead><tbody>${S.users.map(u=>{let a=S.assignments.filter(x=>x.user_id===u.id).map(x=>x.group_name);return `<tr><td>${esc(u.full_name||'Unnamed')}</td><td><span class="badge ${u.role==='admin'?'good':'warn'}">${esc(u.role)}</span></td><td>${esc(a.join(', ')||'—')}</td><td>${u.id===S.profile.id?'Current account':`<button class="text-btn edit-user" data-id="${u.id}">Manage</button>`}</td></tr>`}).join('')}</tbody></table></div>`;$$('.edit-user').forEach(b=>b.onclick=()=>{let u=S.users.find(x=>x.id===b.dataset.id);let assigned=new Set(S.assignments.filter(x=>x.user_id===u.id).map(x=>x.group_name));showModal(`<h3>Manage ${esc(u.full_name||'account')}</h3><form id="userForm" class="form-stack"><label>Role<select id="userRole"><option value="teacher" ${u.role==='teacher'?'selected':''}>Teacher</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option></select></label><div><b style="font-size:.85rem">Assigned classes</b><div class="checkbox-grid" style="margin-top:8px">${groups.map(g=>`<label class="check"><input type="checkbox" name="class" value="${esc(g)}" ${assigned.has(g)?'checked':''}> ${esc(g)}</label>`).join('')}</div></div><button class="btn primary">Save access</button></form>`);$('#userForm').onsubmit=async e=>{e.preventDefault();if(S.demo){toast('Account management needs Supabase');return}let role=$('#userRole').value;let {error}=await sb.from('profiles').update({role}).eq('id',u.id);if(error)return toast(error.message);let d=await sb.from('teacher_classes').delete().eq('user_id',u.id);if(d.error)return toast(d.error.message);let chosen=$$('input[name=class]:checked').map(x=>({user_id:u.id,group_name:x.value}));if(chosen.length){let ins=await sb.from('teacher_classes').insert(chosen);if(ins.error)return toast(ins.error.message)}await loadCloud();closeModal();toast('Access updated');renderUsers()}})}
function renderBackup(){if(S.profile.role!=='admin')return switchView('dashboard');$('#content').innerHTML=`<div class="grid-equal"><section class="panel"><h3>Download full backup</h3><p class="muted">Exports the roster and all attendance currently visible to this admin account as a JSON file.</p><button class="btn primary" id="fullBackup">Download full backup</button></section><section class="panel"><h3>Browser safety copy</h3><p class="muted">After saves and cloud syncs, this device keeps a small last-known snapshot in local browser storage. This is supplementary, not a replacement for Supabase database backups.</p><button class="btn ghost" id="localBackup">Download last browser snapshot</button></section></div><section class="panel" style="margin-top:18px"><h3>Restore / migration notes</h3><p class="muted">The backup is portable JSON. For production recovery, use Supabase/Postgres backup tools. Keep periodic downloaded copies outside the website as an extra safeguard.</p></section>`;$('#fullBackup').onclick=()=>downloadFile(`csi-sunday-school-backup-${iso(new Date())}.json`,JSON.stringify({exported_at:new Date().toISOString(),church:cfg.churchName,people:S.people,attendance:S.attendance},null,2),'application/json');$('#localBackup').onclick=()=>downloadFile(`csi-browser-snapshot-${iso(new Date())}.json`,localStorage.getItem('csi_last_backup')||'{}','application/json')}
function bindProfileLinks(){$$('.profile-link').forEach(b=>b.onclick=()=>showProfile(Number(b.dataset.id)))}
function showProfile(id){const p=S.people.find(x=>x.id===id);if(!p)return;const b=academicBounds(),h=historyForPerson(id,b.start,b.end),rate=calcRate(h),cur=streak(id),best=streak(id,'best');showModal(`<div class="profile-head"><div class="avatar">${initials(p.name)}</div><div><p class="eyebrow">${esc(p.group_name)}</p><h3 style="margin:0">${esc(p.name)}</h3><p class="muted tiny">${esc(p.role)}</p></div></div><div class="profile-kpis"><div class="profile-kpi"><span>Attendance</span><b>${rate}%</b></div><div class="profile-kpi"><span>Present</span><b>${h.filter(x=>statusNorm(x.status)==='Present').length}</b></div><div class="profile-kpi"><span>Current streak</span><b>${cur}</b></div><div class="profile-kpi"><span>Best streak</span><b>${best}</b></div></div><h4 style="margin:22px 0 8px">${esc(b.label)} history</h4><div class="table-wrap"><table style="min-width:0"><thead><tr><th>Date</th><th>Status</th></tr></thead><tbody>${h.slice().sort((a,b)=>b.attendance_date.localeCompare(a.attendance_date)).map(a=>`<tr><td>${fmtDate(a.attendance_date)}</td><td><span class="badge ${statusNorm(a.status)==='Present'?'good':'bad'}">${statusNorm(a.status)}</span></td></tr>`).join('')||'<tr><td colspan="2" class="empty">No attendance yet.</td></tr>'}</tbody></table></div>`)}
init();
})();
