-- CSI Shanthi Church Sunday School — Supabase setup
-- Run this whole file in Supabase SQL Editor on a NEW project.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'Teacher',
  role text not null default 'teacher' check (role in ('admin','teacher')),
  created_at timestamptz not null default now()
);
create table if not exists public.people (
  id bigint generated by default as identity primary key,
  name text not null,
  group_name text not null,
  role text not null default 'Student' check (role in ('Student','Teacher','Volunteer')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  attendance_date date not null,
  status text not null check (status in ('Present','Absent')),
  updated_at timestamptz not null default now(),
  unique(person_id,attendance_date)
);
create table if not exists public.teacher_classes (
  user_id uuid not null references public.profiles(id) on delete cascade,
  group_name text not null,
  primary key(user_id,group_name)
);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into public.profiles(id,full_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email,'@',1)),'teacher') on conflict(id) do nothing;
 return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.profiles where id=auth.uid() and role='admin');
$$;
create or replace function public.can_access_group(g text) returns boolean language sql stable security definer set search_path=public as $$
 select public.is_admin() or exists(select 1 from public.teacher_classes where user_id=auth.uid() and group_name=g);
$$;

alter table public.profiles enable row level security;
alter table public.people enable row level security;
alter table public.attendance enable row level security;
alter table public.teacher_classes enable row level security;

-- Profiles
create policy "profile self read or admin" on public.profiles for select to authenticated using (id=auth.uid() or public.is_admin());
create policy "admins update profiles" on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());
-- Teacher assignments
create policy "assignment self read or admin" on public.teacher_classes for select to authenticated using (user_id=auth.uid() or public.is_admin());
create policy "admins insert assignments" on public.teacher_classes for insert to authenticated with check (public.is_admin());
create policy "admins delete assignments" on public.teacher_classes for delete to authenticated using (public.is_admin());
-- People
create policy "read accessible people" on public.people for select to authenticated using (public.can_access_group(group_name));
create policy "admins insert people" on public.people for insert to authenticated with check (public.is_admin());
create policy "admins update people" on public.people for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete people" on public.people for delete to authenticated using (public.is_admin());
-- Attendance
create policy "read accessible attendance" on public.attendance for select to authenticated using (exists(select 1 from public.people p where p.id=attendance.person_id and public.can_access_group(p.group_name)));
create policy "insert accessible attendance" on public.attendance for insert to authenticated with check (exists(select 1 from public.people p where p.id=attendance.person_id and public.can_access_group(p.group_name)));
create policy "update accessible attendance" on public.attendance for update to authenticated using (exists(select 1 from public.people p where p.id=attendance.person_id and public.can_access_group(p.group_name))) with check (exists(select 1 from public.people p where p.id=attendance.person_id and public.can_access_group(p.group_name)));

-- IMPORTANT: after your first signup, promote that account to admin by replacing the email below:
-- update public.profiles set role='admin' where id=(select id from auth.users where email='YOUR_ADMIN_EMAIL');
